files:

- name:  index
  title: ''

- name:  color-system
  title: colour system
  echo:
  - name: color-system/index

- name:  components
  title: components
  echo:
  - name: components/index

- name:  configuration
  title: configuration
  echo:
  - name: configuration/index

- name:  patterns
  title: patterns
  echo:
  - name: patterns/index
